name: Build & Deploy to GitHub Pages

on:
  push:
    branches: [master, main]

permissions:
  contents: write

jobs:
  node-to-gh:
    runs-on: ubuntu-latest
    name: Build & Deploy to GitHub Pages
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Set your required Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # Make sure you have a build script in your package.json

      - name: Deploy to GitHub Pages
        uses: fdelmazo/node-to-gh-action@v2
        with:
          branch: gh-pages
          folder: build  # Assuming your build output folder is "build" (this may vary based on your setup)
          message: "Automated build deployment to GitHub Pages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides a token for authentication
